language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip freeze"
# command to run tests
script: 
  - python setup.py sdist
  - nosetests
